1628762932457	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=schedule)
1628763086490	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1628763105246	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1628763532464	Sync.Service	DEBUG	User-Agent: Firefox/91.0 (Linux aarch64) FxSync/1.93.0.20210811071140.desktop
1628763532465	Sync.Service	INFO	Starting sync at 2021-08-12 18:18:52 in browser session jFeJZsIq1uGS
1628763532470	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1628763532545	Sync.Status	INFO	Resetting Status.
1628763532546	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1628763532563	FirefoxAccounts	DEBUG	FxAccountsProfileClient: Requested profile
1628763532564	FirefoxAccounts	DEBUG	getOAuthToken enter
1628763532613	FirefoxAccounts	TRACE	getCachedToken returning cached token
1628763532631	FirefoxAccounts	DEBUG	getOAuthToken returning a cached token
1628763532662	Services.Common.RESTRequest	DEBUG	GET request to https://profile.accounts.firefox.com/v1/profile
1628763588577	Services.Common.RESTRequest	DEBUG	GET https://profile.accounts.firefox.com/v1/profile failed: 2152398878 - NS_ERROR_UNKNOWN_HOST
1628763588579	FirefoxAccounts	ERROR	Background refresh of profile failed: {"name":"FxAccountsProfileClientError","code":null,"errno":998,"error":"NETWORK_ERROR","message":"[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]"}
1628763616758	Sync.Resource	WARN	GET request to https://sync-1-us-west1-g.sync.services.mozilla.com/1.5/188195676/info/collections failed: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1628763616760	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1628763616760	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1628763616762	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
1628763616766	Sync.SyncScheduler	DEBUG	Next sync in 600000 ms. (why=reschedule)
1628763616795	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The lookup of the hostname failed"  nsresult: "0x804b001e (NS_ERROR_UNKNOWN_HOST)"  location: "<unknown>"  data: no] No traceback available
